name: Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
      actions: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          pytest --junitxml=test-reports/junit.xml
      - name: Run coverage
        run: |
          pytest --cov=. --cov-report=xml:test-reports/coverage.xml
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-reports/*.xml | test-reports/htmlcov/*.html
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./test-reports/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true